export const searchbarPlaceholders = [
  "Search projects",
  "Find components",
  "Ask AI anything",
  "Search settings",
  "Browse templates",
  "Jump to dashboard",
  "Find documentation",
  "Search commands",
  "Explore integrations",
  "Find team members",
  "Search conversations",
  "Browse collections",
  "Search workflows",
  "Open notifications",
  "Search analytics",
  "Browse examples",
  "Find shortcuts",
  "Search across workspace",
  "Discover new features",
  "Navigate anywhere",
];
